export { default as Home } from './Home'
export { default as PageNotFound } from './PageNotFound'
export { default as Busca } from './Busca'
export { default as Artista } from './Artista'
export { default as LoginCallback } from './LoginCallback'
