export { default as Layout } from './Layout'
export { default as SubHeader } from './SubHeader'
export { default as PrivateRoute } from './PrivateRoute'
export { default as Results } from './ResultArtits'
export { default as DetailsArtist } from './DetailsArtist'
export { default as CardAlbum } from './CardAlbum'
